#pragma once

template <typename T>
void launch_xlstm_block_forward(const T *x,
                                const T *h_prev,
                                const T *c_prev,
                                const T *C_prev,
                                const T *n_prev,
                                T *h,
                                T *c,
                                T *C,
                                T *n,
                                const T *w_proj,
                                const T *w_gate,
                                const T *b_proj,
                                const T *b_gate,
                                const T *w_slstm,
                                const T *w_mlstm,
                                const T *b_slstm,
                                const T *b_mlstm,
                                int batch_size,
                                int input_size,
                                int hidden_size,
                                int proj_size,
                                bool use_mlstm);

template <typename T>
void launch_xlstm_block_backward(const T *grad_h,
                                 const T *h,
                                 const T *c,
                                 const T *C,
                                 const T *n,
                                 const T *x,
                                 const T *w_proj,
                                 const T *w_gate,
                                 const T *w_slstm,
                                 const T *w_mlstm,
                                 T *grad_x,
                                 T *grad_h_prev,
                                 T *grad_c_prev,
                                 T *grad_C_prev,
                                 T *grad_n_prev,
                                 T *grad_w_proj,
                                 T *grad_w_gate,
                                 T *grad_b_proj,
                                 T *grad_b_gate,
                                 T *grad_w_slstm,
                                 T *grad_w_mlstm,
                                 T *grad_b_slstm,
                                 T *grad_b_mlstm,
                                 int batch_size,
                                 int input_size,
                                 int hidden_size,
                                 int proj_size,
                                 bool use_mlstm);
